// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/index.js

(module.exports = require('./namespace'))

.addModules({
  Csv:            require('./csv'),
  SharedLib:      require('./SharedLib'),
  StandardImport: require('./StandardImport')
});
require('./Client');
require('./VibranceStyle');