# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Csv:            require './csv'           
  SharedLib:      require './SharedLib'     
  StandardImport: require './StandardImport'
require './Client'
require './VibranceStyle'