// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Vibrance.Meal.Planner',
  (class Planner extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Client/namespace');
require('./VibranceStyle/namespace');