# generated by Neptune Namespaces v3.x.x
# file: tests/Vibrance.Meal.Planner/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Vibrance.Meal.Planner', class Planner extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
