// generated by Neptune Namespaces v4.x.x
// file: tests/Vibrance.Meal.Planner/namespace.js

module.exports = require('../namespace').addNamespace(
  'Vibrance.Meal.Planner',
  (class Planner extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
