# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/Client/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Client'
.addModules
  Main: require './Main'
require './Components'
require './Models'