// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/Client/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Client'))
.addModules({
  Main: require('./Main')
});
require('./Components');
require('./Models');