# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/Client/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Client'
.addModules
  App:        require './App'       
  Button:     require './Button'    
  HomePage:   require './HomePage'  
  Main:       require './Main'      
  MealPlan:   require './MealPlan'  
  RecipeLine: require './RecipeLine'
require './Models'