# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/VibranceStyle/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  TextPalette:     require './TextPalette'    
  TextStyles:      require './TextStyles'     
  VibrancePalette: require './VibrancePalette'