# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/VibranceStyle/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  VibrancePalette: require './VibrancePalette'
  ViewLayout:      require './ViewLayout'     