// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/VibranceStyle/index.js

(module.exports = require('./namespace'))

.addModules({
  VibrancePalette: require('./VibrancePalette'),
  ViewLayout:      require('./ViewLayout')
});