# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/VibranceStyle/namespace.coffee

module.exports = (require '../namespace').addNamespace('VibranceStyle', class VibranceStyle extends Neptune.PackageNamespace)
