// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/VibranceStyle/namespace.js

module.exports = require('../namespace').addNamespace(
  'VibranceStyle',
  class VibranceStyle extends Neptune.PackageNamespace {}
);
