// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/Client/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  MealPlan:   require('./MealPlan'),
  NavState:   require('./NavState'),
  Recipe:     require('./Recipe'),
  RecipePlan: require('./RecipePlan')
});