# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/Client/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  MealPlan: require './MealPlan'
  Recipe:   require './Recipe'  