# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/Client/Models/namespace.coffee

module.exports = (require '../namespace').addNamespace('Models', class Models extends Neptune.PackageNamespace)
