# generated by Neptune Namespaces v3.x.x
# file: Vibrance.Meal.Planner/Client/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:           require './App'          
  Banner:        require './Banner'       
  Button:        require './Button'       
  ButtonWrapper: require './ButtonWrapper'
  HomePage:      require './HomePage'     
  IconButton:    require './IconButton'   
  Ingredient:    require './Ingredient'   
  MealPlan:      require './MealPlan'     
  RecipePlan:    require './RecipePlan'   
  Recipies:      require './Recipies'     
  Selectable:    require './Selectable'   
  ShoppingList:  require './ShoppingList' 