// generated by Neptune Namespaces v4.x.x
// file: Vibrance.Meal.Planner/Client/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  App:           require('./App'),
  Banner:        require('./Banner'),
  Button:        require('./Button'),
  ButtonWrapper: require('./ButtonWrapper'),
  HomePage:      require('./HomePage'),
  IconButton:    require('./IconButton'),
  Ingredient:    require('./Ingredient'),
  MealPlan:      require('./MealPlan'),
  RecipePlan:    require('./RecipePlan'),
  Recipies:      require('./Recipies'),
  Selectable:    require('./Selectable'),
  ShoppingList:  require('./ShoppingList')
});